name: CI

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: E2E Tests
        env:
          GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
          IMAGE_DESC_VLLM_API: ${{ secrets.IMAGE_DESC_VLLM_API }}
          IMAGE_DESC_MODEL_ID: ${{ secrets.IMAGE_DESC_MODEL_ID }}
          AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
          AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}
        run: yarn test:e2e
